### PR TITLE
Add codecov badge

### PR DESCRIPTION
**Pull request by dfed**
As title

### CODE REVIEW

**Review by bachand — APPROVED** [review]
Approving though it sounds like we're still having some issues with codecov (see https://github.com/dfed/CacheAdvance/pull/67#issuecomment-1275266242) so it may be best if we feel more confident before we add the badge.

Separately, would it be expected that this PR itself has a codecov comment?

**Comment by dfed** [comment]
> Approving though it sounds like we're still having some issues with codecov (see https://github.com/dfed/CacheAdvance/pull/67#issuecomment-1275266242) so it may be best if we feel more confident before we add the badge.

Yup. Going to try to get the other PR working before I merge this.

> Separately, would it be expected that this PR itself has a codecov comment?

That we would! Working on it in #68

**Comment by dfed** [comment]
Now that #68 is merged, I'll get this in once CI goes green again.

**Comment by bachand** [comment]
@dfed I'm wondering how we can avoid this codecov warning?
Screen Shot 2022-10-12 at 2 29 46 PM

It seems like when you pushed https://github.com/dfed/CacheAdvance/pull/69/commits/bb995920d708e0b0425c90b3bf06083911e981a2 we somehow didn't update codecov with the necessary information to recompute code coverage?

I came to that conclusion since that I see that codecov added this warning later, and the original message is comparing https://github.com/dfed/CacheAdvance/commit/ea12b06a3981a8bbedd65cc442c25c8f2539d80b, the previous commit, to the base branch.

Screen Shot 2022-10-12 at 2 30 18 PM

**Comment by bachand** [comment]
If you'd prefer I can file an issue on this too. Not trying to add more work. You've already done some amazing KTLO on this repo this week :)

**Comment by dfed** [comment]
Oh I know what happened here. I merged `main` into this branch, then merged before CI completed since I was only updating the README. 

My guess is that codecov doesn't update posts on closed/merged PRs, so we never got to see the update for the latest commit.

**Comment by bachand** [comment]
Ah OK I'm relieved we have a good theory 👍

**Pull request merged**
